---
####################
# Global things
####################

# Switches
install_prometheus: true
install_grafana: true
install_loki: true
install_alertmanager: true

# Didn't make anything about TLS
# for now it's fine
monitoring_server_fqdn: 10.213.65.63
# Common monitoring user
monitoring_home: "/opt/monitoring"
monitoring_user: "monitoring"
