---

- name: "Create Prometehus cfg dir {{ prometheus_cfg_dir }}"
  file:
    path: "{{ prometheus_cfg_dir }}"
    state: directory
    owner: "{{ monitoring_user }}"
    group: "{{ monitoring_user }}"
  tags:
    - monitoring-server
    - prometheus

- name: "Create Prometehus TSDB data dir {{ prometheus_data_dir }}"
  file:
    path: "{{ prometheus_data_dir }}"
    state: directory
    owner: "{{ prometheus_data_user }}"
    group: "{{ prometheus_data_group }}"
  tags:
    - monitoring-server
    - prometheus

- name: "Copy Prometheus server config {{ prometheus_cfg_dir }}/prometheus.yml"
  template:
    src: "templates/prometheus/prometheus.yml.j2"
    dest: "{{ prometheus_cfg_dir }}/prometheus.yml"
    owner: "{{ monitoring_user }}"
    group: "{{ monitoring_user }}"
    mode: 0644

- name: "Copy Prometheus alerts config {{ prometheus_cfg_dir }}/alerts.yml"
  template:
    src: "templates/prometheus/alerts.yml.j2"
    dest: "{{ prometheus_cfg_dir }}/alerts.yml"
    owner: "{{ monitoring_user }}"
    group: "{{ monitoring_user }}"
    mode: 0644
